<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>CoverFixer</AssemblyName>
    <RootNamespace>CoverFixer</RootNamespace>
    <Version>1.6.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MediaBrowser.Common">
      <HintPath>$(EmbyServerPath)/MediaBrowser.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MediaBrowser.Controller">
      <HintPath>$(EmbyServerPath)/MediaBrowser.Controller.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MediaBrowser.Model">
      <HintPath>$(EmbyServerPath)/MediaBrowser.Model.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration/configPage.html" LogicalName="CoverFixer.Configuration.configPage.html" />
    <EmbeddedResource Include="Configuration/configPage.js" LogicalName="CoverFixer.Configuration.configPage.js" />
  </ItemGroup>
</Project>
